name: tese_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - nltk
  - spacy
  - gensim
  - wordcloud
  - hdbscan
  - pip:
      - emoji
      - rapidfuzz
      - sentence-transformers